(define (knowledge underwater_structure)
  (:problem us10)
  (:unknown-literals

      (state_on v1)
      (state_on v2)
      (state_on v3)
      (state_on v4)
      (state_on v5)
      (state_on v6)
      (state_on v7)
      (state_on v8)
      (state_on v9)
      (state_on v10)

      (strong_current st1)
      (strong_current st2)
      (strong_current st3)
      (strong_current st4)
      (strong_current st5)
      (strong_current st6)
      (strong_current st7)
      (strong_current st8)
      (strong_current st9)
      (strong_current st10)

      (low_visibility st1)
      (low_visibility st2)
      (low_visibility st3)
      (low_visibility st4)
      (low_visibility st5)
      (low_visibility st6)
      (low_visibility st7)
      (low_visibility st8)
      (low_visibility st9)
      (low_visibility st10)
  )
  (:knowledge-updates
      (and
      (oneof (and (structure_located st1) (not (low_visibility st1)) (not (strong_current st1)))
             (and (not (structure_located st1)) (low_visibility st1) (not (strong_current st1)))
             (and (not (structure_located st1)) (not (low_visibility st1)) (strong_current st1))
      )
      (oneof (and (structure_located st2) (not (low_visibility st2)) (not (strong_current st2)))
             (and (not (structure_located st2)) (low_visibility st2) (not (strong_current st2)))
             (and (not (structure_located st2)) (not (low_visibility st2)) (strong_current st2))
      )
      (oneof (and (structure_located st3) (not (low_visibility st3)) (not (strong_current st3)))
             (and (not (structure_located st3)) (low_visibility st3) (not (strong_current st3)))
             (and (not (structure_located st3)) (not (low_visibility st3)) (strong_current st3))
      )
      (oneof (and (structure_located st4) (not (low_visibility st4)) (not (strong_current st4)))
             (and (not (structure_located st4)) (low_visibility st4) (not (strong_current st4)))
             (and (not (structure_located st4)) (not (low_visibility st4)) (strong_current st4))
      )
      (oneof (and (structure_located st5) (not (low_visibility st5)) (not (strong_current st5)))
             (and (not (structure_located st5)) (low_visibility st5) (not (strong_current st5)))
             (and (not (structure_located st5)) (not (low_visibility st5)) (strong_current st5))
      )
      (oneof (and (structure_located st6) (not (low_visibility st6)) (not (strong_current st6)))
             (and (not (structure_located st6)) (low_visibility st6) (not (strong_current st6)))
             (and (not (structure_located st6)) (not (low_visibility st6)) (strong_current st6))
      )
      (oneof (and (structure_located st7) (not (low_visibility st7)) (not (strong_current st7)))
             (and (not (structure_located st7)) (low_visibility st7) (not (strong_current st7)))
             (and (not (structure_located st7)) (not (low_visibility st7)) (strong_current st7))
      )
      (oneof (and (structure_located st8) (not (low_visibility st8)) (not (strong_current st8)))
             (and (not (structure_located st8)) (low_visibility st8) (not (strong_current st8)))
             (and (not (structure_located st8)) (not (low_visibility st8)) (strong_current st8))
      )
      (oneof (and (structure_located st9) (not (low_visibility st9)) (not (strong_current st9)))
             (and (not (structure_located st9)) (low_visibility st9) (not (strong_current st9)))
             (and (not (structure_located st9)) (not (low_visibility st9)) (strong_current st9))
      )
      (oneof (and (structure_located st10) (not (low_visibility st10)) (not (strong_current st10)))
             (and (not (structure_located st10)) (low_visibility st10) (not (strong_current st10)))
             (and (not (structure_located st10)) (not (low_visibility st10)) (strong_current st10))
      )
      (oneof (state_on v1) (and (not (state_on v1))  (valve_closed v1)) )
      (oneof (state_on v2) (and (not (state_on v2))  (valve_closed v2)) )
      (oneof (state_on v3) (and (not (state_on v3))  (valve_closed v3)) )
      (oneof (state_on v4) (and (not (state_on v4))  (valve_closed v4)) )
      (oneof (state_on v5) (and (not (state_on v5))  (valve_closed v5)) )
      (oneof (state_on v6) (and (not (state_on v6))  (valve_closed v6)) )
      (oneof (state_on v7) (and (not (state_on v7))  (valve_closed v7)) )
      (oneof (state_on v8) (and (not (state_on v8))  (valve_closed v8)) )
      (oneof (state_on v9) (and (not (state_on v9))  (valve_closed v9)) )
      (oneof (state_on v10) (and (not (state_on v10))  (valve_closed v10)) )
      )
    )
)
