(define (knowledge neighbourhoods)
  (:problem n_06)
  (:unknown-literals

     (door_closed house0loc0)
     (door_closed house1loc0)
     (door_closed house2loc0)
     (door_closed house3loc0)
     (door_closed house4loc0)
     (door_closed house5loc0)
     (door_closed house6loc0)
     (door_closed house7loc0)
     (door_closed house8loc0)
     (door_closed house9loc0)
     (door_closed house10loc0)
     (door_closed house11loc0)
     (door_closed house12loc0)
     (door_closed house13loc0)
     (door_closed house14loc0)
     (door_closed house15loc0)
     (door_closed house15loc0)
     (door_closed house16loc0)
     (door_closed house17loc0)
     (door_closed house18loc0)
     (door_closed house19loc0)

  )

  (:knowledge-updates
    (and
    (oneof (door_closed house0loc0) (and (not (door_closed house0loc0))  (door_open house0loc0)) )
    (oneof (door_closed house1loc0) (and (not (door_closed house1loc0))  (door_open house1loc0)) )
    (oneof (door_closed house2loc0) (and (not (door_closed house2loc0))  (door_open house2loc0)) )
    (oneof (door_closed house3loc0) (and (not (door_closed house3loc0))  (door_open house3loc0)) )
    (oneof (door_closed house4loc0) (and (not (door_closed house4loc0))  (door_open house4loc0)) )
    (oneof (door_closed house5loc0) (and (not (door_closed house5loc0))  (door_open house5loc0)) )
    (oneof (door_closed house6loc0) (and (not (door_closed house6loc0))  (door_open house6loc0)) )
    (oneof (door_closed house7loc0) (and (not (door_closed house7loc0))  (door_open house7loc0)) )
    (oneof (door_closed house8loc0) (and (not (door_closed house8loc0))  (door_open house8loc0)) )
    (oneof (door_closed house9loc0) (and (not (door_closed house9loc0))  (door_open house9loc0)) )
    (oneof (door_closed house10loc0) (and (not (door_closed house10loc0)) (door_open house10loc0)) )
    (oneof (door_closed house11loc0) (and (not (door_closed house11loc0)) (door_open house11loc0)) )
    (oneof (door_closed house12loc0) (and (not (door_closed house12loc0)) (door_open house12loc0)) )
    (oneof (door_closed house13loc0) (and (not (door_closed house13loc0)) (door_open house13loc0)) )
    (oneof (door_closed house14loc0) (and (not (door_closed house14loc0)) (door_open house14loc0)) )
    (oneof (door_closed house15loc0) (and (not (door_closed house15loc0)) (door_open house15loc0)) )
    (oneof (door_closed house16loc0) (and (not (door_closed house16loc0)) (door_open house16loc0)) )
    (oneof (door_closed house17loc0) (and (not (door_closed house17loc0)) (door_open house17loc0)) )
    (oneof (door_closed house18loc0) (and (not (door_closed house18loc0)) (door_open house18loc0)) )
    (oneof (door_closed house19loc0) (and (not (door_closed house19loc0)) (door_open house19loc0)) )

    )
  )
)
